# Generated by Django 2.2.5 on 2020-01-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principal',
            new_name='principa',
        ),
    ]
