# Generated by Django 2.2.5 on 2020-01-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200113_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
        ),
    ]
