# Generated by Django 2.2.5 on 2020-01-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_valid',
            field=models.BooleanField(default=0),
        ),
    ]
